# Generated by Django 4.0.2 on 2022-03-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
