# Generated by Django 4.0.2 on 2022-04-22 21:24

import a_form.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueId',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=a_form.models.path_and_rename_to_record),
        ),
        migrations.AddField(
            model_name='answer',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=a_form.models.path_and_rename_to_record_signature),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=a_form.models.path_and_rename_to_equipment)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_form.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='unique_id',
            field=models.ForeignKey(default=uuid.UUID('bd405e4d-3116-42aa-a0dc-cec96e4d9a07'), on_delete=django.db.models.deletion.CASCADE, to='a_form.uniqueid', verbose_name='U id'),
        ),
    ]
