# Generated by Django 4.0.2 on 2022-04-22 21:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_form', '0002_uniqueid_remove_answer_question_answer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='unique_id',
            field=models.ForeignKey(default=uuid.UUID('01f33a48-cda5-423f-a44a-1cbc5fc86981'), on_delete=django.db.models.deletion.CASCADE, to='a_form.uniqueid', verbose_name='U id'),
        ),
    ]
