# Generated by Django 4.0.2 on 2022-03-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_form', '0002_remove_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answer/image/%Y/%m/%d'),
        ),
    ]
