# Generated by Django 4.0.2 on 2022-03-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_form', '0003_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
