# Generated by Django 4.0.2 on 2022-04-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_form', '0003_alter_answer_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='unique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_form.uniqueid', verbose_name='Unique'),
        ),
    ]
