# Generated by Django 4.0.2 on 2022-03-29 11:09

import a_form.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_form', '0004_alter_answer_answer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerImage',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=a_form.models.path_and_rename_to_record)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_form.answerimage', verbose_name='Answer Image'),
        ),
    ]
