# Generated by Django 4.0.2 on 2022-03-29 11:15

import a_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_form', '0005_answerimage_alter_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=a_form.models.path_and_rename_to_record),
        ),
        migrations.DeleteModel(
            name='AnswerImage',
        ),
    ]
