# Generated by Django 4.0.2 on 2022-03-30 00:19

import a_form.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_form', '0006_alter_answer_image_delete_answerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=a_form.models.path_and_rename_to_equipment)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_form.equipment')),
            ],
        ),
    ]
